name: deploy-to-gh-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ① 拉源码
      - uses: actions/checkout@v4

      # ② 安装 Hugo extended 0.120.4
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.120.4'
          extended: true

      # ③ 安装 Node（Toha 需要 PostCSS/Sass 等）
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # ④ 生成 package.hugo.json 并拉取前端依赖
      - name: Prepare node modules
        run: |
          hugo mod npm pack          # 生成 package.hugo.json
          npm ci                     # 安装依赖

      # ⑤ 构建站点
      - name: Build site
        run: hugo --minify

      # ⑥ 部署到 gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
