name: deploy-to-gh-pages

on:
  push:
    branches: [main]          # 只要你向 main 推送就触发
  workflow_dispatch:          # 也可以手动点 Run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ① 拉取源码
      - uses: actions/checkout@v4

      # ② 安装 Hugo（extended=true）
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.118.2'
          extended: true

      # ③ 生成静态文件到 /public
      - run: hugo --minify

      # ④ 发布到 gh-pages 分支
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public          # 生成目录
          publish_branch: gh-pages       # 发布分支
          keep_files: true               # ← 这里放在 with 里
